//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gsbRapports
{
    using System;
    using System.Collections.Generic;
    
    public partial class fichefrai
    {
        public fichefrai()
        {
            this.lignefraisforfaits = new HashSet<lignefraisforfait>();
        }
    
        public string idVisiteur { get; set; }
        public string mois { get; set; }
        public Nullable<int> nbJustificatifs { get; set; }
        public Nullable<decimal> montantValide { get; set; }
        public Nullable<System.DateTime> dateModif { get; set; }
        public string idEtat { get; set; }
    
        public virtual etat etat { get; set; }
        public virtual ICollection<lignefraisforfait> lignefraisforfaits { get; set; }
    }
}
