//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gsbRapports
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gsb2021Entities : DbContext
    {
        public gsb2021Entities()
            : base("name=gsb2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<etat> etats { get; set; }
        public DbSet<famille> familles { get; set; }
        public DbSet<fichefrai> fichefrais { get; set; }
        public DbSet<fraisforfait> fraisforfaits { get; set; }
        public DbSet<lignefraisforfait> lignefraisforfaits { get; set; }
        public DbSet<medecin> medecins { get; set; }
        public DbSet<medicament> medicaments { get; set; }
        public DbSet<offrir> offrirs { get; set; }
        public DbSet<rapport> rapports { get; set; }
        public DbSet<visiteur> visiteurs { get; set; }
    }
}
