//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gsbRapports
{
    using System;
    using System.Collections.Generic;
    
    public partial class visiteur
    {
        public visiteur()
        {
            this.rapports = new HashSet<rapport>();
        }
    
        public string id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string login { get; set; }
        public string mdp { get; set; }
        public string adresse { get; set; }
        public string cp { get; set; }
        public string ville { get; set; }
        public Nullable<System.DateTime> dateEmbauche { get; set; }
    
        public virtual ICollection<rapport> rapports { get; set; }
    }
}
